Depend on openjdk instead of java
Eliminates error while tapping
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pivotal/homebrew-tap/trilogy.rb
trilogy: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the pivotal/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/pivotal/homebrew-tap/trilogy.rb:9